version: "3"

volumes:
  db: {}

services:
  db:
    image: mongo:3.5.6
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"

  celery:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    depends_on:
      - rabbit
    command: celery worker -A tasks --concurrency=1 --loglevel=info

  runner:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
      - celery
    command: ["python", "-u", "sentiment_bot.py"]
