version: "3"

volumes:
  db: {}

services:
  db:
    image: mongo:3.5.6
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    restart: unless-stopped

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    restart: unless-stopped

  worker:
      build:
          context: .
          dockerfile: dockerfile
      volumes:
          - .:/app
      links:
          - rabbit
      depends_on:
          - rabbit
